language: node_js

node_js:
  - "8"

sudo: required
addons:
  chrome: stable

cache: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
  local_dir: public

before_script:
  - wget https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/bin/
  - export CHROME_BIN=chromium-browser
  - npm install -g gulp-cli

script:
  - npm run test:ci
  - npm run lint:styles
  - npm run build-ghpages
  - npm run build-patternfly
  - npm run build:ie11

after_success:
  - ./build/deploy.sh

before_deploy:
  - cd $TRAVIS_BUILD_DIR
