version: 2

# Adapted from https://github.com/circleci/circleci-docs/blob/master/.circleci/config.yml
# I'd love to find docs on this syntax.
references:
  js_deps_paths: &js_deps_paths
  - node_modules/
  build_cache_paths: &build_cache_paths
  - .cache/
  - dist/
  - public/
  - src/icons/PfIcons/
  js_deps_cache_key: &js_deps_cache_key
    js-deps-v{{.Environment.CACHE_VERSION}}-{{checksum "package-lock.json"}}
  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/project

workflows:
  version: 2
  build_test_deploy:
    jobs:
    - build
    - test_a11y:
        requires:
        - build
    - lint:
        requires:
        - build
    - deploy:
        requires:
        - build
        - test_a11y
        filters:
          branches:
            only: v4
jobs:
  build:
    docker:
    - image: circleci/node:10-browsers
    steps:
    - checkout
    - persist_to_workspace:
        root: ~/project
        paths:
          - "*"
    - restore_cache:
        keys:
        - *js_deps_cache_key
    - run:
        name: Conditional install
        command: if [ ! -d node_modules ]; then npm ci; fi
    - save_cache:
        paths: *js_deps_paths
        key: *js_deps_cache_key
    - run:
        name: Build Dist
        command: npm run build-patternfly
    - run:
        name: Build IE11
        command: npm run build:ie11
    - run:
        name: Build Site
        command: npm run build:site
    - run:
        name: Upload docs
        command: node .circleci/upload-preview.js public
        when: always
    - persist_to_workspace:
        root: ~/project
        paths: *build_cache_paths
  test_a11y:
    docker:
    - image: circleci/node:10-browsers
    steps:
    - *attach_workspace
    - restore_cache:
        keys:
        - *js_deps_cache_key
    - run:
        name: a11y Tests
        command: npm run test:a11y:ci
    - run:
        name: Upload a11y report
        command: node .circleci/upload-preview.js coverage
        when: always
    - store_artifacts:
        path: coverage/
    - persist_to_workspace:
        root: ~/project
        paths:
          - coverage/
  lint:
    docker:
    - image: circleci/node:10
    steps:
      - *attach_workspace
      - restore_cache:
          keys:
          - *js_deps_cache_key
      - run:
          name: Lint SASS
          command: npm run lint:sass
      - run:
          name: Lint JS
          command: npm run lint:js
          when: always
      - run:
          name: Lint CSS
          command: npm run lint:css
          when: always
      - run:
          name: Lint CSS Size
          command: .circleci/css-size-report/sizeReport.js run
          when: always
      - store_artifacts:
          path: .circleci/css-size-report/report.html
          destination: lint
      - run:
          name: Breaking Change Lint
          # https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
          command: |
              if git log origin/master..HEAD --format="%b" | grep -i "breaking change";
              then
                  echo "Breaking change above detected"
                  exit 1
              fi
          when: always
  deploy:
    docker:
    - image: circleci/node:10
    steps:
    - *attach_workspace
    - run:
        name: Avoid Unknown Host for github.com
        command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    - run:
        name: Release to NPM
        command: npx semantic-release@17.0.4
