name: promote
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:        
      - v6.*
jobs:
  build-and-promote:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN_REDALLEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/checkout@v4
      - name: Build for promotion
        run: yarn install --immutable && yarn build
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - name: Manual publish
        run: |
          cd dist
          npm version ${{ github.ref_name }} --git-tag-version false
          npm publish --tag latest
        env:
          HUSKY: 0
